heat_template_version: 2013-05-23

description: Template to spawn an Fedora instance.

parameters:
  metadata:
    type: json

  image:
    type: string

  flavor:
    type: string

  key_name:
    type: string

  PrivateNetwork:
    type: string
    description: project network to attach instance to
    default: private

  PublicNetwork:
    type: string
    description: network used for floating IPs
    default: public

resources:
  VM:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      metadata: { get_param: metadata }
      networks:
        - port: { get_resource: Port }

  Port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: PrivateNetwork }
      security_groups:
        - default

  PublicIPAllocation:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: PublicIPAllocation }

  PublicIPAssociation:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: PublicIPAllocation }
      port_id: { get_resource: Port }

