heat_template_version: 2013-05-23

description: |
  Create a simple VM with Security Groups for 2 ports (22 & 80)

parameters:
  KeyName:
    type: string
    description: SSH Keys for VM
    default: KP-OCB-02

  VMName:
    type: string
    description: Name of VM
    default: vm-config-01

  Network:
    type: string
    description: Network to attach VM
    default: lan

  Flavor:
    type: string
    description: Flavor of VM
    default: s1.cw.small-1

  Image:
    type: string
    description: ID of OS image
    default: 19556f03-e92d-4fb9-b86a-c10dd91f8e21

resources:
  IPf-Allocation:
    type: OS::Nova::FloatingIP
    properties:
      pool: public

  IPf-Association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: IPf-Allocation }
      server_id: { get_resource: VM }

  SecurityGroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: SG to simple VM
      description: Ports (ingress) of access & web access, ports (egress) open by default
      rules:
        - remote_ip_prefix: { get_resource: IPf-Association }
          direction: ingress
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: { get_resource: IPf-Association }
          direction: ingress
          protocol: tcp
          port_range_min: 80
          port_range_max: 80


  VM:
    type: OS::Nova::Server
    properties:
      image: { get_param: Image }
      flavor: { get_param: Flavor }
      key_name: { get_param: KeyName }
      name: { get_param: VMName }
      networks:
        - network: { get_param: Network }
      user_data_format: SOFTWARE_CONFIG
      # software_config_transport: POLL_SERVER_HEAT

outputs:
  Result:
    value:
      get_attr: [VMDeployment, result]
