# Fiche: F05
heat_template_version: 2013-05-23

description: >
  HOT template to create a new neutron network plus a router to the public
  network, and for deploying one server into the new network. The template also
  assigns floating IP addresses to each server so they are routable from the
  public network.

parameters:
  VM_Name:
    type: string
    description: Name of VM to be created
    label: VM_Name = Name of VM
    default: LB-VM00

  Private_Net_Name:
    type: string
    description: Name of Private Network to be created
    label: Private_Net_Name = Name of Private Network
    default: LB-Net00

resources:
  Private_Net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: Private_Net_Name }

  Private_Subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: Private_Net }
      cidr: "10.0.9.0/24"

  Router_Interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: 80523c26-3933-40ba-ba18-833245fe504c
      subnet_id: { get_resource: Private_Subnet }

  VM:
    type: OS::Nova::Server
    properties:
      name: { get_param: VM_Name }
      image: "66137275-909d-466b-a2f5-abdda6865011"
      flavor: "t1.tiny.small-2"
      key_name: "KP-OMC-01"
      networks:
        - port: { get_resource: VM_Port }

  VM_Port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: Private_Net }
      fixed_ips:
        - subnet_id: { get_resource: Private_Subnet }

  VM_Floating_IP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: "net-pub"
      port_id: { get_resource: VM_Port }

outputs:
  VM_Private_IP:
    description: IP address of server1 in private network
    value: { get_attr: [ VM, first_address ] }

  VM_Public_IP:
    description: Floating IP address of server1 in public network
    value: { get_attr: [ VM_Floating_IP, floating_ip_address ] }
